export interface CommitResult {
  type: string;
  scope: string | null;
  subject: string;
  body: string[];
  confidence: number;
}

export function ruleBasedCommit(diff: string): CommitResult {
  const lower = diff.toLowerCase();

  const type =
    lower.includes("test") || lower.includes("spec")         ? "test"     :
    lower.includes("fix")  || lower.includes("bug")          ? "fix"      :
    lower.includes("readme") || lower.includes(".md")        ? "docs"     :
    lower.includes("refactor") || lower.includes("rename")   ? "refactor" :
    lower.includes("chore") || lower.includes("package.json")? "chore"    :
    "feat";

  const scopeMatch = diff.match(/diff --git a\/(?:src\/|lib\/|app\/)?(\w+)/);
  const scope = scopeMatch ? scopeMatch[1] : null;

  const added   = (diff.match(/^\+[^+]/gm) || []).length;
  const removed = (diff.match(/^-[^-]/gm)  || []).length;

  return {
    type,
    scope,
    subject: `${type} changes in ${scope ?? "codebase"}`,
    body: [
      `${added} line${added !== 1 ? "s" : ""} added, ${removed} line${removed !== 1 ? "s" : ""} removed`,
      "Generated by rule-based mode (--no-ai)",
    ],
    confidence: 60,
  };
}
